# Environnement
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY 
exec systemctl --user import-environment XDG_CURRENT_DESKTOP

# Services système
exec /usr/libexec/xfce-polkit
exec ~/.config/waybar/scripts/dnf-status
exec wl-paste --watch cliphist store

# Utilitaires
exec gammastep   
exec mako

# Tiling
exec autotiling &
