bind=SUPER,Return,spawn,foot
bind=SUPER,e,spawn,thunar
bind=SUPER,d,spawn,rofi -show drun -config $HOME/.config/rofi/applications-menu.rasi 
bind=SUPER,code:52,spawn,geany

bind=NONE,XF86HomePage,spawn,brave-origin
bind=NONE,XF86Tools,spawn,aimp
bind=NONE,XF86Mail,spawn,thunderbird
bind=NONE,XF86Messenger,spawn,discord
bind=NONE,Print,spawn,$HOME/.config/mango/scripts/screenshot.sh
bind=NONE,XF86Calculator,spawn,galculator

bind=SUPER,Escape,spawn,foot --hold btop
bind=SUPER,r,reload_config
bind=SUPER,f,togglefullscreen
bind=SUPER,code:38,killclient,
bind=SUPER,space,togglefloating

circle_layout=tile,scroller,dwindle
bind=SUPER,t,setlayout,tile
bind=SUPER,l,switch_layout

bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down   

bind=SUPER,code:24,spawn,$HOME/.config/rofi/scripts/alarm-window
bind=SUPER,s,spawn,$HOME/.config/rofi/scripts/system-menu
bind=SUPER,g,spawn,$HOME/.config/sway/scripts/guitar
bind=SUPER,h,spawn,$HOME/.config/rofi/scripts/show-keybinding
bind=SUPER,c,spawn,$HOME/.config/rofi/scripts/menu-config
bind=SUPER,v,spawn_shell,cliphist list | rofi -dmenu -p "󰏢 Clipboard" -config .config/rofi/clipboard.rasi | cliphist decode | wl-copy
bind=SUPER,b,spawn,$HOME/.config/rofi/scripts/web-menu
bind=SUPER,p,spawn,$HOME/.config/rofi/scripts/mango-powermenu

bind=SUPER,y,spawn,foot -e yazi
bind=SUPER,i,spawn,foot -e yazi Info
bind=SUPER,n,spawn,nm-connection-editor

bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5

bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5

bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=SHIFT,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle
