layerrule=noblur:1,layer_name:waybar
layerrule=isnoborder:1,layer_name:swayosd-client

windowrule=isfloating:1,appid:galculator
windowrule=isfloating:1,appid:xfce-polkit
windowrule=isfloating:1,appid:nm-connection-editor
windowrule=isfloating:1,appid:nwg-look
windowrule=isfloating:1,appid:pavucontrol
windowrule=isfloating:1,appid:steam,title:"Liste de contacts"
windowrule=isfloating:1,appid:thunar,title:Confirmer*
windowrule=isfloating:1,appid:thunar,title:Opération*
windowrule=isfloating:1,appid:thunar,title:Renommer*
windowrule=isfloating:1,appid:xarchiver
windowrule=isfloating:1,appid:xdg-desktop-portal-gtk
